AllCops:
  Exclude:
    - 'Gemfile'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/routes.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/StringLiterals:
  Exclude:
    - 'db/migrate/**/*'

Layout/EmptyLines:
  Exclude:
    - 'db/migrate/**/*'
