AllCops:
  Exclude:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/routes.rb'
    - 'db/seeds.rb'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Style/StringLiterals:
  Exclude:
    - 'db/migrate/**/*'

Layout/EmptyLines:
  Exclude:
    - 'db/migrate/**/*'
